DOMAIN-SUFFIX,ipv4.duiadns.net
DOMAIN-SUFFIX,ipv6-test.pl
DOMAIN-SUFFIX,ipv6.br
DOMAIN-SUFFIX,test-ipv6.alpinedc.ch
DOMAIN-SUFFIX,test-ipv6.arauc.br
DOMAIN-SUFFIX,test-ipv6.belwue.net
DOMAIN-SUFFIX,test-ipv6.carnet.hr
DOMAIN-SUFFIX,test-ipv6.cgates.lt
DOMAIN-SUFFIX,test-ipv6.ch
DOMAIN-SUFFIX,test-ipv6.cl
DOMAIN-SUFFIX,test-ipv6.com
DOMAIN-SUFFIX,test-ipv6.com.au
DOMAIN-SUFFIX,test-ipv6.csclub.uwaterloo.ca
DOMAIN-SUFFIX,test-ipv6.cz
DOMAIN-SUFFIX,test-ipv6.do.ayepv6.com
DOMAIN-SUFFIX,test-ipv6.epic.network
DOMAIN-SUFFIX,test-ipv6.fratec.net
DOMAIN-SUFFIX,test-ipv6.freerangecloud.com
DOMAIN-SUFFIX,test-ipv6.go6.si
DOMAIN-SUFFIX,test-ipv6.hkg.vr.org
DOMAIN-SUFFIX,test-ipv6.hu
DOMAIN-SUFFIX,test-ipv6.in
DOMAIN-SUFFIX,test-ipv6.is
DOMAIN-SUFFIX,test-ipv6.iu13.net
DOMAIN-SUFFIX,test-ipv6.ke.liquidtelecom.ne
DOMAIN-SUFFIX,test-ipv6.ke.liquidtelecom.net
DOMAIN-SUFFIX,test-ipv6.micso.network
DOMAIN-SUFFIX,test-ipv6.nl
DOMAIN-SUFFIX,test-ipv6.noroutetohost.net
DOMAIN-SUFFIX,test-ipv6.ro
DOMAIN-SUFFIX,test-ipv6.roedu.net
DOMAIN-SUFFIX,test-ipv6.se
DOMAIN-SUFFIX,test-ipv6.sin.vr.org
DOMAIN-SUFFIX,test-ipv6.ttk.ru
DOMAIN-SUFFIX,test-ipv6.vu.ayepv6.com
DOMAIN-SUFFIX,testipv6.cn
DOMAIN-SUFFIX,testipv6.de
DOMAIN,ipv4-test-ipv6.eurobilltracker.com
DOMAIN,ipv6-test-ipv6.eurobilltracker.com
DOMAIN,ipv6-test.com
DOMAIN,ipv6.duiadns.ne
DOMAIN,ipv6.joram.it
DOMAIN,ipv6.mudgee.host
DOMAIN,ipv6.nsx.de
DOMAIN,ipv6.stdio.be
DOMAIN-SUFFIX,v6test.snozzages.com
DOMAIN-SUFFIX,test-ipv6.ams.vr.org
DOMAIN-SUFFIX,test-ipv6.tld.sk
